import UNDPColorModule from 'undp-viz-colors';

export const SSCOLOR = [
  {
    value: 'Poverty and Inequality',
    textColor: UNDPColorModule.sdgColors.sdg1,
  },
  {
    value: 'Governance',
    textColor: UNDPColorModule.sdgColors.sdg16,
  },
  {
    value: 'Resilience',
    textColor: UNDPColorModule.sdgColors.sdg16,
  },
  {
    value: 'Environment',
    textColor: UNDPColorModule.sdgColors.sdg14,
  },
  {
    value: 'Energy',
    textColor: UNDPColorModule.sdgColors.sdg7,
  },
  {
    value: 'Gender Equality',
    textColor: UNDPColorModule.sdgColors.sdg5,
  },
  {
    value: 'Strategic Innovation',
    textColor: UNDPColorModule.categoricalColors.colors[0],
  },
  {
    value: 'Digitalisation',
    textColor: UNDPColorModule.categoricalColors.colors[1],
  },
  {
    value: 'Development Financing',
    textColor: UNDPColorModule.categoricalColors.colors[2],
  },
  {
    value: 'Others',
    textColor: '#000000',
  },
];

export const HORIZONTYPE = {
  '2021-2022': 'Short Term',
  '2022-2023': 'Short Term',
  '2023-2025': 'Medium Term',
  '2024-2025': 'Medium Term',
  '2026-2030': 'Long Term',
};

export const MONTHS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

export const NO_OF_ITEMS_IN_PAGE = 25;

export const CHOICES = {
  units: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belize',
    'Benin',
    'BERA',
    'Bermuda',
    'Bhutan',
    'BMS',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'BPPS',
    'Brazil',
    'Brunei Darussalam',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chief Digital Office',
    'Chief Digital Office (CDO)',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Cook Islands',
    'Costa Rica',
    'Côte d’Ivoire',
    'Crisis Bureau (CB)',
    'Cuba',
    'Curacao and Sint Maarten',
    'Cyprus (project office)',
    'Democratic Republic of Congo',
    'Development financing',
    'Djibouti',
    'Dom. Republic',
    'DPRK',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Eswatini',
    'Ethiopia',
    'Executive Office (ExO)',
    'External',
    'Federated States of Micronesia',
    'Fiji MCO',
    'Future Fellows',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Global Centre for Technology, Innovation and Sustainable Development (Singapore)',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Guyana-Suriname',
    'Haiti',
    'Honduras',
    'Human Development Report Office (HDRO)',
    'Independent Evaluation Office (IEO)',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Istanbul International Center for Private Sector in Development (Istanbul, Turkey)',
    'Jamaica',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo (as per UNSCR 1244)',
    'Kuwait',
    'Kyrgyzstan',
    'Lao PDR',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Malaysia MCO',
    'Maldives',
    'Mali',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Mongolia',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Nairobi Global Centre on Resilient Ecosystems and Desertification (Nairobi, Kenya)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'North Macedonia',
    'Office of Audit and Investigations (OAI)',
    'Oslo Governance Centre (Oslo, Norway)',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'People',
    'Peru',
    'Philippines',
    'PNG',
    'Prog for Palestinian',
    'Regional Bureau for Africa, New York, USA',
    'Regional Bureau for Arab States, New York, USA',
    'Regional Bureau for Asia and the Pacific, New York',
    'Regional Bureau for Europe and the CIS, New York, USA',
    'Regional Bureau for Latin America and the Caribbean, New York, USA',
    'Regional Centre: Panama City, Panama',
    'Regional Hub: Amman, Jordan',
    'Regional Hub: Bangkok, Thailand',
    'Regional Hub: Dakar, Senegal',
    'Regional Hub: Istanbul, Turkey',
    'Regional Hub: Nairobi, Kenya',
    'Regional Hub: Pretoria, South Africa',
    'Regional Service Centre: Addis Ababa, Ethiopia',
    'Republic of Belarus',
    'Republic of Cape Verde',
    'Republic of Montenegro',
    'Republic of South Sudan',
    'Republic of the',
    'Republic of the Sudan',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia and Saint Vincent',
    'Samoa MCO',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Sri Lanka',
    'Suriname',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'The Bahamas',
    'the British Virgin Islands',
    'the Commonwealth of Dominica',
    'the Grenadines',
    'Timor Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad & Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'UNDP Nordic Representation Office (Copenhagen, Denmark)',
    'UNDP Office in Geneva (Geneva, Switzerland)',
    'UNDP Representation Office in Brussels (Brussels, Belgium)',
    'UNDP Representation Office in Japan (Tokyo, Japan)',
    'UNDP Seoul Policy Centre for Knowledge Exchange through SDG Partnerships (Seoul, Republic of Korea)',
    'UNDP Washington Representation Office (Washington, USA)',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Viet Nam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],
};

export const SIGNAL_ORDER_BY_OPTIONS = [
  {
    key: 'created_at',
    value: 'Created On',
  },
  {
    key: 'modified_at',
    value: 'Modified On',
  },
  {
    key: 'steep',
    value: 'STEEP+V',
  },
  {
    key: 'signature_primary',
    value: 'Primary Signature Solution',
  },
];

export const TREND_ORDER_BY_OPTIONS = [
  {
    key: 'created_at',
    value: 'Created On',
  },
  {
    key: 'modified_at',
    value: 'Modified On',
  },
  {
    key: 'time_horizon',
    value: 'Time Horizon',
  },
  {
    key: 'impact_rating',
    value: 'Impact Rating',
  },
];

export const WEB_ADDRESS =
  'https://thankful-forest-05a90a303.3.azurestaticapps.net';

export const API_ACCESS_TOKEN = process.env.INPUT_ACCESS_TOKEN_FOR_API;
// export const API_ACCESS_TOKEN = import.meta.env.VITE_ACCESS_CODE;
export const REDIRECT_URL = process.env.INPUT_REDIRECT_URI_FOR_MSAL;
// export const REDIRECT_URL = import.meta.env.VITE_REDIRECT_URL;
